CACHE_TIMEOUT_MINUTE = 60
CACHE_TIMEOUT_HOUR = CACHE_TIMEOUT_MINUTE * 60
CACHE_TIMEOUT_DAY = CACHE_TIMEOUT_HOUR * 24
CACHE_TIMEOUT_WEEK = CACHE_TIMEOUT_DAY * 7
CACHE_TIMEOUT_MONTH = CACHE_TIMEOUT_DAY * 30
