version: '3.8'

services:
  bot:
    container_name: bot-container
    build: .
    command: >
              bash -c "poetry run python manage.py makemigrations &&
                      poetry run python manage.py migrate &&
                      poetry run python bot.py"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
  
  celery:
    build: .
    command: poetry run celery -A config worker -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
      - db
      - bot
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


volumes:
  postgres_data:
