# Generated by Django 5.1.3 on 2024-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmodels', '0003_remove_userprofile_name_userprofile_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
