# Generated by Django 5.1.3 on 2024-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmodels', '0004_alter_userprofile_chat_id_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
