# Generated by Django 5.1.3 on 2024-12-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botmodels', '0005_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgsetting',
            name='last_task_eta',
            field=models.DateTimeField(null=True),
        ),
    ]
